const defaults={kwp:10,specificYield:1000,pvCost:14500,degradation:.4,consumption:4200,extraConsumption:2500,directShare:28,electricityPrice:.32,feedIn:.08,priceGrowth:2,opex:180,years:20,batteryEnabled:true,batteryKwh:10,batteryCost:6500,batteryEfficiency:90,batteryCycles:220};
const ids=["kwp","specificYield","pvCost","degradation","consumption","extraConsumption","directShare","electricityPrice","feedIn","priceGrowth","opex","years","batteryKwh","batteryCost","batteryEfficiency","batteryCycles"];
const state={...defaults}; const dec={kwp:1,specificYield:0,pvCost:0,degradation:2,consumption:0,extraConsumption:0,directShare:0,electricityPrice:2,feedIn:3,priceGrowth:2,opex:0,years:0,batteryKwh:1,batteryCost:0,batteryEfficiency:0,batteryCycles:0};
const euro=(v,d=0)=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:d}).format(v); const num=(v,d=0)=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:d}).format(v); const pct=(v,d=0)=>num(v,d)+" %";
function sync(){ids.forEach(id=>{document.getElementById(id).value=state[id];document.getElementById(id+"Num").value=state[id]});document.getElementById("batteryEnabled").checked=state.batteryEnabled;outputs()}
function outputs(){ids.forEach(id=>{const o=document.querySelector(`output[data-for="${id}"]`);if(!o)return;let s="";if(id==="kwp")s=" kWp";else if(id==="specificYield")s=" kWh/kWp";else if(["pvCost","opex","batteryCost"].includes(id))s=" €";else if(["consumption","extraConsumption"].includes(id))s=" kWh";else if(["degradation","directShare","priceGrowth","batteryEfficiency"].includes(id))s=" %";else if(["electricityPrice","feedIn"].includes(id))s=" €/kWh";else if(id==="years")s=" Jahre";else if(id==="batteryKwh")s=" kWh";else if(id==="batteryCycles")s=" Zyklen";o.textContent=num(state[id],dec[id])+s})}
function bind(){ids.forEach(id=>{const r=document.getElementById(id),n=document.getElementById(id+"Num");const set=v=>{v=parseFloat(v);if(Number.isNaN(v))return;state[id]=v;r.value=v;n.value=v;outputs();calc()};r.addEventListener("input",e=>set(e.target.value));n.addEventListener("input",e=>set(e.target.value))});document.getElementById("batteryEnabled").addEventListener("change",e=>{state.batteryEnabled=e.target.checked;calc()})}
function yearFlow(year,withBat,override={}){const production=state.kwp*state.specificYield*Math.pow(1-state.degradation/100,year-1),demand=state.consumption+state.extraConsumption,direct=Math.min(demand,production*state.directShare/100);let stored=0;if(withBat&&state.batteryEnabled){const surplus=Math.max(0,production-direct),unmet=Math.max(0,demand-direct),throughput=state.batteryKwh*state.batteryCycles;stored=Math.min(unmet,surplus*state.batteryEfficiency/100,throughput*state.batteryEfficiency/100)}const draw=stored/(state.batteryEfficiency/100||1),exportKwh=Math.max(0,production-direct-draw),selfUsed=direct+stored,gridBuy=Math.max(0,demand-selfUsed),price0=override.electricityPrice??state.electricityPrice,price=price0*Math.pow(1+state.priceGrowth/100,year-1),annualNet=selfUsed*price+exportKwh*state.feedIn-state.opex;return{production,demand,direct,stored,exportKwh,selfUsed,gridBuy,annualNet}}
function irr(cfs){let lo=-.99,hi=2;const npv=r=>cfs.reduce((s,cf,i)=>s+cf/Math.pow(1+r,i),0);let a=npv(lo),b=npv(hi);if(a*b>0)return null;for(let i=0;i<100;i++){const m=(lo+hi)/2,n=npv(m);if(Math.abs(n)<1e-7)return m;if(n*a>0){lo=m;a=n}else{hi=m;b=n}}return(lo+hi)/2}
function scenario(withBat,override={}){const years=Math.max(1,Math.round(state.years)),investment=state.pvCost+(withBat&&state.batteryEnabled?state.batteryCost:0),cash=[-investment],cum=[-investment],flows=[];let c=-investment,pay=null;for(let y=1;y<=years;y++){const f=yearFlow(y,withBat,override);flows.push(f);cash.push(f.annualNet);c+=f.annualNet;cum.push(c);if(pay===null&&c>=0){const prev=cum[cum.length-2];pay=(y-1)+(-prev/(f.annualNet||1))}}const first=flows[0];return{investment,cash,cum,flows,pay,totalProfit:c,irr:irr(cash),selfRate:first.production?first.selfUsed/first.production*100:0,autarky:first.demand?first.selfUsed/first.demand*100:0,year1:first.annualNet,first}}
const payText=v=>v===null?"> "+Math.round(state.years)+" J.":num(v,1)+" Jahre",irrText=v=>v===null?"–":pct(v*100,1);
function calc(){const pv=scenario(false),bat=scenario(true),en=state.batteryEnabled;annualProduction.textContent=num(pv.first.production)+" kWh";annualDemand.textContent=num(pv.first.demand)+" kWh";pvInvestment.textContent=euro(state.pvCost);pvSelfUse.textContent=pct(pv.selfRate);pvAutarky.textContent=pct(pv.autarky);pvYear1.textContent=euro(pv.year1);pvPayback.textContent=payText(pv.pay);pvProfit.textContent=euro(pv.totalProfit);pvIrr.textContent=irrText(pv.irr);batSelfUse.textContent=en?pct(bat.selfRate):"deaktiviert";batAutarky.textContent=en?pct(bat.autarky):"–";batYear1.textContent=en?euro(bat.year1):"–";batPayback.textContent=en?payText(bat.pay):"–";batProfit.textContent=en?euro(bat.totalProfit):"–";batIrr.textContent=en?irrText(bat.irr):"–";batteryScenario.classList.toggle("disabled",!en);batteryLegend.style.display=en?"inline":"none";batteryFields.style.opacity=en?"1":".42";batteryFields.style.pointerEvents=en?"auto":"none";heroPayback.textContent=payText(pv.pay);heroProfit.textContent=euro(pv.totalProfit);heroAutarky.textContent=en?pct(bat.autarky):pct(pv.autarky);insight(pv,bat,en);table(pv,bat,en);cashChart(pv,bat,en);energyChartDraw(en?bat:pv,en);sensitivity()}
function insight(pv,bat,en){let t;if(!en)t=`Die PV-Anlage erreicht im Modell ${pct(pv.autarky)} Autarkie und ${payText(pv.pay)} Amortisationszeit.`;else{const d=bat.totalProfit-pv.totalProfit,a=bat.autarky-pv.autarky;t=d>0?`Der Speicher erhöht den Autarkiegrad um ${num(a)} Prozentpunkte und verbessert den kumulierten Vorteil im Zeitraum um ${euro(d)}.`:`Der Speicher erhöht den Autarkiegrad um ${num(a)} Prozentpunkte, reduziert aber den kumulierten wirtschaftlichen Vorteil im Zeitraum um ${euro(Math.abs(d))}.`}insightText.textContent=t}
function table(pv,bat,en){const rows=[["Investition",euro(pv.investment),en?euro(bat.investment):"–"],["Eigenverbrauchsquote",pct(pv.selfRate),en?pct(bat.selfRate):"–"],["Autarkiegrad",pct(pv.autarky),en?pct(bat.autarky):"–"],["Netzbezug Jahr 1",num(pv.first.gridBuy)+" kWh",en?num(bat.first.gridBuy)+" kWh":"–"],["Einspeisung Jahr 1",num(pv.first.exportKwh)+" kWh",en?num(bat.first.exportKwh)+" kWh":"–"],["Amortisation",payText(pv.pay),en?payText(bat.pay):"–"],[`Vorteil nach ${Math.round(state.years)} Jahren`,euro(pv.totalProfit),en?euro(bat.totalProfit):"–"],["Interne Rendite",irrText(pv.irr),en?irrText(bat.irr):"–"]];compareBody.innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join("")}
function prep(id){const c=document.getElementById(id),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(320,rect.width),h=id==="cashflowChart"?Math.min(420,w*.5):Math.min(350,w*.72);c.width=w*dpr;c.height=h*dpr;c.style.height=h+"px";const x=c.getContext("2d");x.setTransform(dpr,0,0,dpr,0,0);return{x,w,h}}
const css=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim(),short=v=>Math.abs(v)>=1000?Math.round(v/1000)+"k €":Math.round(v)+" €";
function cashChart(pv,bat,en){const{x,w,h}=prep("cashflowChart"),all=en?[...pv.cum,...bat.cum]:pv.cum;let min=Math.min(...all,0),max=Math.max(...all,0),pad=(max-min)*.12||1000;min-=pad;max+=pad;const m={l:58,r:18,t:18,b:38},pw=w-m.l-m.r,ph=h-m.t-m.b;x.font="12px system-ui";for(let i=0;i<=4;i++){const y=m.t+ph*i/4;x.strokeStyle="#dbe3ee";x.beginPath();x.moveTo(m.l,y);x.lineTo(w-m.r,y);x.stroke();x.fillStyle="#64748b";x.fillText(short(max-(max-min)*i/4),6,y+4)}for(let i=0;i<=state.years;i+=Math.max(1,Math.ceil(state.years/5)))x.fillText(i+" J.",m.l+pw*i/state.years-8,h-12);const zero=m.t+ph*max/(max-min);x.strokeStyle="#94a3b8";x.beginPath();x.moveTo(m.l,zero);x.lineTo(w-m.r,zero);x.stroke();const line=(data,color)=>{x.beginPath();x.strokeStyle=color;x.lineWidth=3;data.forEach((v,i)=>{const px=m.l+pw*i/(data.length-1),py=m.t+ph*(max-v)/(max-min);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()};line(pv.cum,css("--accent"));if(en)line(bat.cum,css("--blue"))}
function energyChartDraw(sc,en){const{x,w,h}=prep("energyChart"),vals=[sc.first.direct,en?sc.first.stored:0,sc.first.exportKwh],cols=[css("--accent"),css("--blue"),"#cbd5e1"],tot=vals.reduce((a,b)=>a+b,0)||1,cx=w/2,cy=h/2,r=Math.min(w,h)*.31,inner=r*.62;let a=-Math.PI/2;vals.forEach((v,i)=>{const da=v/tot*Math.PI*2;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,r,a,a+da);x.closePath();x.fillStyle=cols[i];x.fill();a+=da});x.beginPath();x.arc(cx,cy,inner,0,Math.PI*2);x.fillStyle="#fff";x.fill();x.textAlign="center";x.fillStyle="#0f172a";x.font="700 24px system-ui";x.fillText(num(sc.selfRate)+" %",cx,cy-3);x.font="12px system-ui";x.fillStyle="#64748b";x.fillText("Eigenverbrauch",cx,cy+18);x.textAlign="start"}
function sensitivity(){const{x,w,h}=prep("sensitivityChart"),base=state.electricityPrice,prices=[.7,.85,1,1.15,1.3].map(f=>base*f),data=prices.map(p=>scenario(false,{electricityPrice:p}).totalProfit),m={l:55,r:15,t:20,b:46},pw=w-m.l-m.r,ph=h-m.t-m.b,min=Math.min(0,...data),max=Math.max(1,...data);x.font="11px system-ui";for(let i=0;i<=4;i++){const y=m.t+ph*i/4;x.strokeStyle="#dbe3ee";x.beginPath();x.moveTo(m.l,y);x.lineTo(w-m.r,y);x.stroke();x.fillStyle="#64748b";x.fillText(short(max-(max-min)*i/4),4,y+4)}const bw=pw/data.length*.56;data.forEach((v,i)=>{const px=m.l+pw*(i+.5)/data.length-bw/2,py=m.t+ph*(max-v)/(max-min||1),zero=m.t+ph*max/(max-min||1);x.fillStyle=css("--accent");x.fillRect(px,Math.min(py,zero),bw,Math.abs(zero-py));x.fillStyle="#64748b";x.textAlign="center";x.fillText(euro(prices[i],2),px+bw/2,h-14)});x.textAlign="start"}
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.dataset.panel===b.dataset.tab))}));function load(){Object.assign(state,defaults);sync();calc()}resetBtn.addEventListener("click",load);loadExample.addEventListener("click",load);loadExampleTop.addEventListener("click",()=>{load();rechner.scrollIntoView({behavior:"smooth"})});addEventListener("resize",calc);bind();sync();calc();
